{% set version = "3.1.5" %}
{% set major_minor_version = '.'.join(version.split('.')[:2]) %}
{% set version_no_dot = version | replace(".", "") %}

package:
  name: wxwidgets
  version: {{ version }}

source:
  url: https://github.com/wxWidgets/wxWidgets/releases/download/v{{ version }}/wxWidgets-{{ version }}.tar.bz2
  sha256: d7b3666de33aa5c10ea41bb9405c40326e1aeb74ee725bb88f90f1d50270a224

build:
  number: 0
  # OSX Still doesn't work, see https://github.com/conda-forge/wxwidgets-feedstock/pulls
  skip: true  # [osx]
  run_exports:
    # ABI seems to be stable between minor versions
    - {{ pin_subpackage('wxwidgets', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake        # [win]
    - ninja        # [win]
    - make         # [unix]
    - pkg-config   # [unix]

    # Necessary CDTs
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxinerama-devel') }}     # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]

  host:
    - zlib
    - libpng
    - libtiff
    - expat
    # hmaarrfk 2020/05/25
    # Even after we specify that we want to use sys jpeg
    # conda claims we are still overlinking on windows
    # not too sure why
    - jpeg
    - libiconv    # [unix]
    - xz          # [unix]
    - glib        # [unix]
    - pango       # [unix]
    - cairo       # [unix]
    - fontconfig  # [unix]
    - gdk-pixbuf  # [unix]
    - gtk3        # [unix]
    - libglu       # [linux]
    - mesalib      # [unix]
    - xorg-libx11  # [linux]
    - xorg-libsm   # [linux]
    - xorg-libxi   # [linux]
  run:
    - fontconfig
    - pango
    - gtk3         # [linux]
    - xorg-libx11  # [linux]
    - xorg-libsm   # [linux]

test:
  commands:
    - test -f ${PREFIX}/lib/libwx_baseu-{{ major_minor_version }}${SHLIB_EXT}  # [linux]
    # Not sure why OSX is adding these extra modifiers to SHLIB
    # This is the reason why we aren't including the OSX package in conda-forge just yet.
    # - test -f ${PREFIX}/lib/libwx_baseu-{{ version }}.0.0${SHLIB_EXT}          # [osx]
    - test -f ${PREFIX}/include/wx-{{ major_minor_version }}/wx/wx.h           # [unix]
    - wx-config --prefix  # [unix]
    - wxrc --help  # [unix]
    - where wxrc   # [win]
    - if not exist %LIBRARY_BIN%\\wxrc.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\wxmsw{{ version_no_dot }}u_xrc_vc_x64_custom.dll exit 1  # [win]

about:
  home: https://www.wxwidgets.org/
  license: LicenseRef-wxWindows
  license_family: LGPL
  license_file:
    - docs/licence.txt
    - docs/lgpl.txt
    - docs/gpl.txt
  summary: Cross-Platform GUI Library

  description: |
    wxWidgets is a C++ library that lets developers create applications for
    Windows, macOS, Linux and other platforms with a single code base. It has
    popular language bindings for Python, Perl, Ruby and many other languages,
    and unlike other cross-platform toolkits, wxWidgets gives applications a
    truly native look and feel because it uses the platform's native API rather
    than emulating the GUI. It's also extensive, free, open-source and mature.
  doc_url: https://docs.wxwidgets.org/
  dev_url: https://github.com/wxWidgets/wxWidgets/

extra:
  recipe-maintainers:
    - hmaarrfk
